#! /bin/bash

. ./var/conf

list_types() {
    list_items_in_dir ${RCLM_PREFIX}/share/rclm2/types
    if [ -d ${HOME}/.rclm2/types ]; then
	list_items_in_dir ${HOME}/.rclm2/types
    fi
}

if [ $# -ne 1 ]; then
    cat <<EOF
Usege: $0 <LEAGUE_TYPE>

 <LEAGUE_TYPE> List.
EOF
    list_types
else
    echo $1
    src=""
    if [ -x ${RCLM_PREFIX}/share/rclm2/types/$1/start ]; then
	src=${RCLM_PREFIX}/share/rclm2/types/$1
    elif [ -x ${HOME}/.rclm2/types/$1/start ]; then
	src=${HOME}/.rclm2/types/$1
    else
	echo 'unknown LEAGUE TYPE "'$1'" .'
	exit 1
    fi
    test -e ./script/game && rm -rf ./script/game
    ${INSTALL} $src ./script/game

    # 
    test -e ./script/schedule || ./script/init_scheduler roundrobin
    # test -e ./script/announce || ./script/init_announce console
    # test -e ./script/confirm  || ./script/init_confirm  console
fi
